### PR TITLE
Refactoring and documentation

### PR DESCRIPTION
**Pull request by ProjectMutilation**

### CODE REVIEW

**Review by vsysoev — COMMENTED** [review]
Why we move from camel case to underscore in function name? Is it required by pep8 or other style guides?

**Comment by vsysoev** [comment]
https://realpython.com/python-pep8/#naming-conventions
Found recommendation )

**Comment by ProjectMutilation** [comment]
> Why we move from camel case to underscore in function name? Is it required by pep8 or other style guides?

python way, camelCase only for legacy

**Review by vsysoev — APPROVED** [review]
LGFM (Looks Good for Me)

**Pull request merged**
